Add view with Pug + webpack css
frontend-park-mail-ru/2017_2_brainstorm pull request #10
Opened 2017-10-14 22:09 UTC by akenoq

2017-10-15 19:23 UTC, Antonboom commented on changelog.txt
> +View на pug
Забыла вырезать у изображений белый центр солнышка)

2017-10-15 19:25 UTC, Antonboom commented on .gitignore
>  # Webpack result script
Забыла вырезать у изображений белый центр солнышка)
И у букв тоже

2017-10-15 19:39 UTC, Antonboom requested changes
Есть вопросы

2017-10-15 19:39 UTC, Antonboom commented on .gitignore
>  # Webpack result script
Забыла вырезать у изображений белый центр солнышка)
И у букв тоже

2017-10-15 19:39 UTC, Antonboom commented on static/views/register-page/register-page.pug
> +    img.register-page__button-back_img(src="./../../img/back_2.png")
Можно вынести в css как background.
А на обработку изображений в css есть отдельный лоадер

2017-10-15 19:39 UTC, Antonboom commented on static/index.html
>          <div class="main-page page" hidden>
Не логичней оставить один div и менять только его содержимое?

2017-10-15 19:39 UTC, Antonboom commented on static/views/main-page/MainPage.js
> +        let template = require("./main-page.pug");
Т.е. хочешь сказать, я не могу вынести в Page templatePath и render() {... require(this.templatePath) }?

2017-10-15 19:39 UTC, Antonboom commented on static/script/MainApp.js
> +import "./../styles/style.css";
Зачем импортить стили в JS? 
Вроде явно нигде их не используешь, а шаблоны у тебя app.css используют

2017-10-15 19:47 UTC, akenoq commented on static/script/MainApp.js
> +import "./../styles/style.css";
Без этого вебпак их не собирал

2017-10-15 19:47 UTC, akenoq commented on .gitignore
>  # Webpack result script
:)

2017-10-15 19:48 UTC, akenoq commented on static/views/main-page/MainPage.js
> +        let template = require("./main-page.pug");
Да, так

2017-10-15 19:56 UTC, akenoq commented on static/index.html
>          <div class="main-page page" hidden>
Мб. Постараюсь поправить

2017-10-20 11:26 UTC, akenoq commented on .gitignore
>  # Webpack result script
Поправлю позже на фш

2017-10-20 11:27 UTC, akenoq commented on static/index.html
>          <div class="main-page page" hidden>
Теперь один div в index.html

2017-10-20 11:30 UTC, akenoq commented on static/views/register-page/register-page.pug
> +    img.register-page__button-back_img(src="./../../img/back_2.png")
Пока так оставила

2017-10-21 16:08 UTC, merged