Add single & saving theme
frontend-park-mail-ru/2017_2_brainstorm pull request #13
Opened 2017-10-24 10:35 UTC by akenoq

2017-10-25 17:12 UTC, Antonboom commented on static/game-modules/GameManager.js
> +        this.ww = ww;
Что такое ww, hh?
Width, Height?

2017-10-25 17:20 UTC, Antonboom requested changes
Cool!

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/GameManager.js
> +        this.ww = ww;
Что такое ww, hh?
Width, Height?

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/GameManager.js
> +                case 65:
KEY_A_KEY_CODE
Используешь этот код в разных местах - удобнее же вынести

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/GameManager.js
> +            const k = event.keyCode;
event.keyCode единый для всех браузеров?

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/GameManager.js
> +        this.renderer.setClearColor("#ffbe74");
BACKGROUND_COLOR

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/GameManager.js
> +    addObjectsGeneration() {
addBubblesGeneration?

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/GameManager.js
> +}
Кажется, линтер спит

2017-10-25 17:20 UTC, Antonboom commented on static/game-modules/ObjectsCreater.js
> +        let cubeGeometry = new THREE.CubeGeometry(size, size, size);
Интереснее было бы сделать отдельные классы для куба, сферы и пр.
Наследуешься от абстрактной фигуры и пр.
Твои мысли?

Или хотя бы просто, чтобы я не видел копипасты кода как здесь и ниже

2017-10-25 17:31 UTC, akenoq commented on static/game-modules/GameManager.js
> +        this.ww = ww;
Да это размерности, так удобнее

2017-10-25 17:31 UTC, akenoq commented on static/game-modules/GameManager.js
> +        this.ww = ww;
Могу заменить

2017-10-25 17:32 UTC, akenoq commented on static/game-modules/GameManager.js
> +    addObjectsGeneration() {
Ок

2017-10-25 17:37 UTC, akenoq commented on static/game-modules/GameManager.js
> +            const k = event.keyCode;
Да, это стандартно

2017-10-25 23:15 UTC, akenoq commented on static/game-modules/GameManager.js
> +                case 65:
Ок

2017-10-25 23:26 UTC, akenoq commented on static/game-modules/GameManager.js
> +                case 65:
Поправила

2017-10-25 23:26 UTC, akenoq commented on static/game-modules/GameManager.js
> +        this.renderer.setClearColor("#ffbe74");
Ок

2017-10-26 14:35 UTC, akenoq commented on static/game-modules/ObjectsCreater.js
> +        let cubeGeometry = new THREE.CubeGeometry(size, size, size);
Добавила метод, который создает обьект

2017-10-26 15:10 UTC, Antonboom commented on static/game-modules/GameManager.js
> +                    case 1:
mmmmagick number

2017-10-26 15:10 UTC, merged