Reg, Auth, pages: records, info, play
frontend-park-mail-ru/2017_2_brainstorm pull request #3
Opened 2017-09-14 14:03 UTC by akenoq

2017-09-14 20:14 UTC, Antonboom requested changes
1. Структура проекта:
```
src (source)
    script.js
    app.js
dst (destination)
    index.min.js
static:
     html
     css
     images
```
2. Используй стрелочные функции и остальные хипстерские штуки из ES6. Прежде, чем писать цикл, подумай - а не могу ли я это сделать map’ом или еще как?
3. Со следующим пулл-реквестом хотелось бы видеть линтер: https://eslint.org
4. Имена переменных: не длинные и не короткие, понятные. Код самочитаем. Никаких objVariable (и так понятно, что obj). Куда приятнее видеть elem или element вместо el и пр.
5. Научись правильно называть классы и методы! Называй класс так, как хочешь, чтобы назывался сам объект. Кошка (и у нее метод погладить()), а не класс ПогладитьКотенка.

2017-09-14 20:14 UTC, Antonboom commented on .gitignore
> +.idea
Для таких штук в домашней директории есть .gitignore_global, у тебя же нет проекта, в котором ты хочешь не эксклудить .idea?)

Вот пример моего
```
$ cat ~/.gitignore_global 
# OS generated files #
######################
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
.idea
.idea/
collected_static
node_modules
```

2017-09-14 20:14 UTC, Antonboom commented on Procfile
> +web: node index.js
Этот файл больше не нужен. Мы же точно не руками раскладываем на хероку 🔥 ?

2017-09-14 20:14 UTC, Antonboom commented on .travis.yml
> +- echo "Hello World!"
В script должен быть прогон тестов или настройка деплоя:
```
npm test
```
Сейчас он свалится (подправить package.json)

2017-09-14 20:14 UTC, Antonboom commented on package.json
> +  "description": "",
Где описание?
Где репозиторий? (npm WARN BubbleRise@1.0.0 No repository field)

2017-09-14 20:14 UTC, Antonboom commented on package.json
> +  "keywords": [],
Где ключевые слова? Кто автор?

2017-09-14 20:14 UTC, Antonboom commented on package.json
> +    "webpack": "^3.5.6"
Зачем тебе в продакшене webpack?

2017-09-14 20:14 UTC, Antonboom commented on package.json
> +  "version": "1.0.0",
Жду в проекте changelog.txt, меняющийся при каждом пулл-реквесте, вида 
```
2.0.0
Всё переписано на нормальный язык вроде Java

1.0.1
Добавлена валидация для форм

1.0.0
Добавлены основные страницы
Настроен вебпак
```
В зависимости от него будем менять версию в package.json, посмотрим, какая она будет в итоге.
Про обозначение версий: google "мажор минор патч"

2017-09-14 20:14 UTC, Antonboom commented on static/.idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Сравни свой .gitignore и мой .gitignore_global и объясни, почему эти .idea файлы попали сюда

2017-09-14 20:14 UTC, Antonboom commented on static/.idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Выпилить всю .idea!

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +<html lang="en">
Ты не русские символы используешь?

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +                    <img src="img/login.png" style="width: 100%;">
Никаких inline-стилей! У тебя такой красивый БЭМ, тем более

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +            <br>
Не используй ```<br>```.
Лучше добавь margin-bottom блоку выше. С - стили

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +                <span class="register-page__link-to-login">Sign In</span>
Забыт закрывающий тег ```</p>```?

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +            <table border="1" bgcolor="#e6e6fa" align="center">
Как насчет вынести это в records-page__table?

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +            <div class="play-page__play-yard">
Ты имела в виду play-field? :)

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +</html>
Здесь и **далее**.
За отсутствие пустой строки в конце файла бью по рукам.

2017-09-14 20:14 UTC, Antonboom commented on webpack.config.js
> +module.exports = {
Крутой конфиг! Не вижу использование babel, хотя он есть в зависимостях. Как насчет минификации файлов?
Плюс не вижу .babelrc
А еще в самом конфиге можно использовать ES6 (убрать module.exports) - не подскажешь, как?)

2017-09-14 20:14 UTC, Antonboom commented on index.js
> +console.log("Server works on port " + port);
Все  выводы в console, если это не обработка ошибок, пожалуйста, в DEBUG-моде.
Нет настройки какой сейчас мод (гуглить в сторону ENV), значит не пушим мне в мастер DEBUG-мусор.
Тем более вроде morgan используешь...

2017-09-14 20:14 UTC, Antonboom commented on index.js
> +let port = process.env.PORT || 5050;
5050 в константу наверх вида APPLICATION_PORT или как будет удобнее назвать.

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +
К чему тут пустая строка?

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +
Обычно стиль такой:
```
block
     block

     block

     block
block
```

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +    <div class="footer" align="center">brainstorm&copy;2017</div>
Wiki [говорит](https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D1%80%D0%B0%D0%B2%D0%BE), что формат у копирайта такой:
(c) Компания, 2017

2017-09-14 20:14 UTC, Antonboom commented on static/index.html
> +    <script src="./script/ResultScript.js"></script>
Почему он в CamelCase? Там что, класс?
Обычно получившемуся скрипту дают имена вроде bundle.min.js, app.js, app.min.js, index.js и пр.

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +export default class AddEvent {
Вопрос стиля, но т.к. в файле может быть несколько экспортов, их удобней видеть в одном месте, например, в самом низу
```
class Event {};

export default Event;
```
Ты так не считаешь?

2017-09-14 20:14 UTC, Antonboom commented on static/script/GetElem.js
> +export default class GetElem {
Я бы сделал это GetElementMixin'ом, чтобы от него можно было наследоваться и получать методы типа getElementByClass, getElemById и пр.

2017-09-14 20:14 UTC, Antonboom commented on static/script/GetElem.js
> +    getEl(className) {
Не бойся понятных и не слишком длинных имен, памяти на всех хватит!
getElemByClass куда понятнее, чем getEl от чего-то там.

И тебе среда не подсвечивает, что он может быть static? 
Ты не используешь внутри this - сделай метод статичным, почему нет?

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +import GetElem from "./GetElem.js";
Необязательно указывать в конце расширение .js
И определись какие строки и где ты используешь (одинарные или двойные кавычки) - единобразие в коде. (Например, для импорта только двойные, в коде - только одинарные, или везде одинарные и пр.)

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +    constructor() {
Класс, который ты написала, является аналогом Router'а (переключателя страниц). Быть может, именно такое название он должен носить, а не странное AddEvent (что вообще означает глагол, а не существительное).

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +        document.getElementsByClassName('main-page')[0].hidden = true;
Почему ты не используешь свой GetElem?

А еще, ряд однотипных действий вроде этого так и напрашиваются на цикл, слабо?

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +        const t = this;
Используй [стрелочные функции](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions) и тебе не придется прокидывать this.

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +        const objGetElem = new GetElem();
А был бы миксин (вспомогательный класс-родитель), можно было бы просто писать this.getElemByClass() и не плодить каждый раз объекты.

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +"use strict";
Babel разве не сам добавляет тебе 'use strict'; во все файлы? Видимо ты его не используешь?

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +        const objReqUser = new RequestToHost();
Не нужно у всего подряд писать obj - и так понятно, что это объект!

2017-09-14 20:14 UTC, Antonboom commented on static/script/RequestToHost.js
> +export default class RequestToHost {
Подход интересный, но не совсем правильный. Express должен лишь раздавать статику для тебя (его впоследствии заменит nginx) и выдавать один единственный index.html, в котором один единственный index.min.js, в котором в дело вступает Роутер, который меняет странички в зависимости от урла (или #хэша) в адресной строке.

Этот класс мы потом переделаем для взаимодействия с бекендом, но сейчас не нужно ходить к самой себе за страничками - у нас SPA!

2017-09-14 20:14 UTC, Antonboom commented on static/script/CorrectLoginPassword.js
> +            if (this.validData.indexOf(login[i]) === -1) {
Пожалуйста, познакомься с миром [регулярных выражений](https://learn.javascript.ru/regular-expressions-javascript).
Этот цикл можно заменить на одну проверку соответствия регулярке.

2017-09-14 20:14 UTC, Antonboom commented on static/script/CorrectLoginPassword.js
> +        for (let i = 0; i < password.length; i++) {
Тебе не кажется жестоким  разрешать делать _простые_ пароли (лишь из символов и цифр)?

2017-09-14 20:14 UTC, Antonboom commented on static/script/CorrectLoginPassword.js
> +export default class CorrectLoginPassword {
Нужно научиться называть классы, методы и переменные.
Хочу, чтобы это превратилось в класс формы (LoginForm), у которой есть поля (LoginField, PasswordField), у них есть метод validate() и т.д. и т.п.

2017-09-14 20:14 UTC, Antonboom commented on static/script/CorrectLoginPassword.js
> +        return "ok";
Если это сообщения - в константу класса.
Но в таких методах обычно бросают исключения, которые отлавливаются выше.

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +            t.showOnlyOnePage("info-page");
Зачем два раза показывать info-page?

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +        objGetElem.getEl("main-menu__button-play").addEventListener("click", function(){
Сделай метод, который принимает класс кнопки и страницу - и вешает соответствующий слушатель.
Меньше повторяющегося кода!

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +    addEventToLoginPageButtons() {
Все эти методы должны стать отдельными объектами класса Page, которые внутри уже реализуют всю эту логику.
Роутер обращается с Page'ами.

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +                        return errBox.innerHTML = "Некорректный ввод или логин уже существует";
Все сообщения в константы (например, INVALID_LOGIN_ERR)

2017-09-14 20:14 UTC, Antonboom commented on static/script/AddEvent.js
> +                    objGetElem.getEl("register-form__input-login").value = "";
Одни и те же действия, попахивает методом объекта класса Field - empty(). Или просто функцией makeEmpty(className).

2017-09-18 20:21 UTC, akenoq commented on package.json
> +  "version": "1.0.0",
done

2017-09-18 20:21 UTC, akenoq commented on .gitignore
> +.idea
ok

2017-09-18 20:21 UTC, akenoq commented on package.json
> +  "description": "",
добавлено

2017-09-18 20:21 UTC, akenoq commented on package.json
> +  "keywords": [],
добавлены

2017-09-18 20:24 UTC, akenoq commented on static/.idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
сделано

2017-09-18 20:25 UTC, akenoq commented on static/index.html
> +<html lang="en">
пока убрала lang

2017-09-18 20:26 UTC, akenoq commented on static/index.html
> +                    <img src="img/login.png" style="width: 100%;">
fixed

2017-09-18 20:26 UTC, akenoq commented on static/index.html
> +
подправлен html

2017-09-18 20:26 UTC, akenoq commented on static/index.html
> +            <br>
ok

2017-09-18 20:27 UTC, akenoq commented on static/index.html
> +                <span class="register-page__link-to-login">Sign In</span>
fixed

2017-09-18 20:27 UTC, akenoq commented on static/index.html
> +            <table border="1" bgcolor="#e6e6fa" align="center">
ок

2017-09-18 20:28 UTC, akenoq commented on static/index.html
> +
fixed

2017-09-18 20:28 UTC, akenoq commented on static/index.html
> +    <div class="footer" align="center">brainstorm&copy;2017</div>
fixed

2017-09-18 20:29 UTC, akenoq commented on static/index.html
> +    <script src="./script/ResultScript.js"></script>
согласен, было странновато - теперь app.js

2017-09-18 20:31 UTC, akenoq commented on webpack.config.js
> +module.exports = {
пока без babel
про module.exports пока не знаю :Р

2017-09-18 20:31 UTC, akenoq commented on index.js
> +let port = process.env.PORT || 5050;
done

2017-09-18 20:34 UTC, akenoq commented on index.js
> +console.log("Server works on port " + port);
убрала выводы в консоль
на клиенте написан класс Debugger, который использую при отладке

2017-09-18 20:34 UTC, akenoq commented on static/script/AddEvent.js
> +"use strict";
пока без Babel

2017-09-18 20:35 UTC, akenoq commented on static/script/AddEvent.js
> +import GetElem from "./GetElem.js";
определюсь :+1:

2017-09-18 20:36 UTC, akenoq commented on static/script/AddEvent.js
> +    constructor() {
теперь PagePresenter

2017-09-18 20:37 UTC, akenoq commented on static/script/AddEvent.js
> +        document.getElementsByClassName('main-page')[0].hidden = true;
сделано

2017-09-18 20:38 UTC, akenoq commented on static/script/AddEvent.js
> +        const objGetElem = new GetElem();
сделан миксин elementPresenter

2017-09-18 20:39 UTC, akenoq commented on static/script/AddEvent.js
> +        const t = this;
попробую :+1:

2017-09-18 20:40 UTC, akenoq commented on static/script/AddEvent.js
> +            t.showOnlyOnePage("info-page");
fixed

2017-09-18 20:42 UTC, akenoq commented on static/script/AddEvent.js
> +    addEventToLoginPageButtons() {
ок, создам класс Page и его методы уже будут навешивать ивенты

2017-09-18 20:44 UTC, akenoq commented on static/script/AddEvent.js
> +                    objGetElem.getEl("register-form__input-login").value = "";
добавлены методы clear...(...fields)

2017-09-18 20:45 UTC, akenoq commented on static/script/GetElem.js
> +export default class GetElem {
done

2017-09-18 20:45 UTC, akenoq commented on static/script/GetElem.js
> +    getEl(className) {
ок

2017-09-18 20:46 UTC, akenoq commented on static/script/RequestToHost.js
> +export default class RequestToHost {
сделано по аналогу примера с лекции

2017-09-19 11:44 UTC, Antonboom commented on static/script/RequestToHost.js
> +export default class RequestToHost {
@akenoq 
Так, это я напутал. Показалось, что ты отдаешь JSON для формирования страничек - а это просто заглушка для бекенда, скопипасченная с кода Анатолия.

Надеюсь, ты понимаешь, как это все работает? Или может, стоит пописать тесты?

2017-09-24 08:55 UTC, akenoq commented on static/script/AddEvent.js
> +    addEventToLoginPageButtons() {
теперь страницы - обьекты класса Page

2017-09-24 08:55 UTC, akenoq commented on static/script/CorrectLoginPassword.js
> +export default class CorrectLoginPassword {
ok, созданы классы для форм

2017-09-24 12:56 UTC, akenoq commented on static/script/CorrectLoginPassword.js
> +            if (this.validData.indexOf(login[i]) === -1) {
Исправлено на регулярки

2017-09-24 13:01 UTC, akenoq commented on static/script/AddEvent.js
> +        const objReqUser = new RequestToHost();
Исправлено

2017-09-24 13:03 UTC, akenoq commented on static/script/CorrectLoginPassword.js
> +        return "ok";
ок

2017-09-24 13:05 UTC, akenoq commented on static/script/AddEvent.js
> +                    objGetElem.getEl("register-form__input-login").value = "";
миксин fieldsCleaner для очистки полей

2017-09-24 16:13 UTC, Antonboom commented on static/script/RegisterForm.js
>              alert("Вы успешно зарегистрировались!");
Константа

2017-09-24 16:14 UTC, Antonboom commented on static/script/Validator.js
> +        this.validData += this.validData.toUpperCase() + "1234567890";
this.validData где-то используется?

2017-09-24 16:15 UTC, Antonboom commented on static/script/Validator.js
> +        if (/^[a-z0-9]{3,16}$/i.test(password)) {
Почему такой слабый пароль! Где остальные символы??!?!

2017-09-24 16:16 UTC, Antonboom commented on static/script/app.js
>  /******/ 	__webpack_require__.p = "";
Почему этот файл вообще попадает в систему контроля версий? Он собирается вебпаком, незачем засорять репозиторий

2017-09-24 16:17 UTC, Antonboom commented on static/script/LoginForm.js
>              alert("Вы вошли на сайт!");
Константа

2017-09-24 16:19 UTC, Antonboom commented on .travis.yml
> +- echo "Hello World!"
script:
    npm test

2017-09-24 16:21 UTC, Antonboom commented on static/script/LoginForm.js
> +        let log = this.correctLog(logValue);
Что за log, что за pas?
Мир не рухнет, если это будет login и password/pass.
Что за correctLog? Ты проверяешь логи?
🔥

2017-09-24 16:22 UTC, Antonboom commented on static/script/LoginForm.js
> +        const t = this;
Я уже писал про стрелочные функции и this

2017-09-24 16:26 UTC, Antonboom commented on static/script/LoginForm.js
> +            t.clearFields("login-form__input-login", "login-form__input-password", "login-form__error-box");
68 и 72 один и тот же код -> новая функция
https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself

2017-09-24 16:29 UTC, Antonboom commented on webpack.config.js
> +module.exports = {
Ладно, там нужен бабель
и тогда можно webpack.config.babel.js

2017-09-24 16:29 UTC, Antonboom commented on webpack.config.js
> +		filename: "./static/script/app.js"
И за гитигнорь этот файл!

2017-09-24 16:30 UTC, Antonboom commented on static/script/messages.js
> +const messagesLoginForm = {
Удобней хранить такие сообщения в самом классе формы в виде static, или хотя бы в том же файле вместе с формой в виде const

2017-09-24 16:31 UTC, Antonboom commented on static/script/whoamiMixin.js
> +            const logBox = t.getElementByClass("main-page__user");
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2017-09-24 16:33 UTC, Antonboom commented on static/script/Validator.js
> +        this.OK = "ok";
Что это такое? Сообщение? Статус? Что?
OK_STATUS
RESPONSE_OK
OK_MESSAGE
OK_MSG

2017-09-24 16:33 UTC, Antonboom commented on static/script/Validator.js
> +        this.validData += this.validData.toUpperCase() + "1234567890";
this.validData где-то используется?

2017-09-24 16:34 UTC, Antonboom commented on static/script/Validator.js
> +        if (login==="") {
```
if (!login) {
}
```

2017-09-24 16:35 UTC, Antonboom commented on static/script/Validator.js
> +        if (/^[a-zA-Z][a-zA-Z0-9]{3,10}/.test(login)) {
Например
```
return (/^[a-zA-Z][a-zA-Z0-9]{3,10}/.test(login) ? this.RESPONSE_OK : this. RESPONSE_INCORRECT);
```

2017-09-24 16:37 UTC, Antonboom commented on static/script/fieldsCleaner.js
> +            if (elem.nodeName === "INPUT") {
Был бы отдельный класс поля и проблем бы не было

2017-09-24 16:38 UTC, Antonboom commented on static/script/Validator.js
> +export default class CorrectLoginPassword {
Что за названия?
LoginValidator
PasswordValidator

2017-09-24 16:38 UTC, Antonboom commented on static/script/RequestToHost.js
> +                return callback(xhr, null);
Коды ответа в константы.

2017-09-24 16:39 UTC, Antonboom commented on static/script/RequestToHost.js
> +            if (xhr.readyState !== 4) return;
Никаких однострочников
```javascript
if () {
    return;
}
```

2017-09-24 16:40 UTC, Antonboom commented on static/script/RequestToHost.js
> +            const response = JSON.parse(xhr.responseText);
Здесь и ниже три одинаковых куска кода, обрабатывающих запрос.
Не хватает общей функции apiRequest()

2017-09-24 16:41 UTC, Antonboom commented on static/script/RegisterForm.js
> +            errorBox.innerHTML = messagesRegisterForm.EMPTY_MESSAGE;
Как насчет выводить ошибки отдельно для каждого поля (под полем, например)?

2017-09-24 16:49 UTC, Antonboom commented on static/script/PagePresenter.js
> +            {button: "records-page__button-back", nextPage: "main-page"}
Как насчет отдельного
```javascript
class RecordsPage extends BasePage {
}
```
BasePage предоставляет основные функции вроде whoami()
и без множественного наследования

2017-09-24 19:04 UTC, akenoq commented on static/script/Validator.js
> +        this.validData += this.validData.toUpperCase() + "1234567890";
уже нет - забыла убрать

2017-09-24 19:05 UTC, akenoq commented on static/script/app.js
>  /******/ 	__webpack_require__.p = "";
ок, уберу

2017-09-24 19:08 UTC, akenoq commented on static/script/Validator.js
> +        if (/^[a-z0-9]{3,16}$/i.test(password)) {
ок, добавлю

2017-09-24 19:32 UTC, akenoq commented on static/script/Validator.js
> +        this.OK = "ok";
._. ok, исправлю

2017-09-24 19:33 UTC, akenoq commented on static/script/Validator.js
> +        this.validData += this.validData.toUpperCase() + "1234567890";
нет уже

2017-09-24 20:00 UTC, akenoq commented on static/script/RequestToHost.js
> +export default class RequestToHost {
да, там все понятно было

2017-09-24 20:16 UTC, akenoq commented on static/script/Validator.js
> +export default class CorrectLoginPassword {
старое осталось - исправлю

2017-09-24 20:19 UTC, akenoq commented on static/script/RequestToHost.js
> +            if (xhr.readyState !== 4) return;
ok

2017-09-24 23:53 UTC, akenoq commented on static/script/messages.js
> +const messagesLoginForm = {
@Antonboom, ок, могу переделать. Думала, что это good прием.
Модуль с константами не принято делать? Оо

2017-09-25 00:35 UTC, akenoq commented on webpack.config.js
> +		filename: "./static/script/app.js"
@Antonboom, app.js?

2017-09-25 01:05 UTC, akenoq commented on static/script/AddEvent.js
> +        objGetElem.getEl("main-menu__button-play").addEventListener("click", function(){
Метод в классе Page

2017-09-25 01:09 UTC, akenoq commented on static/script/app.js
>  /******/ 	__webpack_require__.p = "";
done

2017-09-25 01:10 UTC, akenoq commented on static/script/LoginForm.js
> +        let log = this.correctLog(logValue);
fixed

2017-09-25 01:10 UTC, akenoq commented on static/script/LoginForm.js
> +            t.clearFields("login-form__input-login", "login-form__input-password", "login-form__error-box");
Добавлен метод clearForm

2017-09-25 01:13 UTC, akenoq commented on static/script/Validator.js
> +        if (/^[a-zA-Z][a-zA-Z0-9]{3,10}/.test(login)) {
done

2017-09-25 05:31 UTC, Antonboom commented on webpack.config.js
> +		filename: "./static/script/app.js"
@akenoq, да, тот что собирается

2017-09-25 05:34 UTC, Antonboom commented on static/script/messages.js
> +const messagesLoginForm = {
@akenoq, когда эти константы могут шариться между различными модулями - да. И когда их не миллион в одном файле.
Т.е., например "const HTTP_OK = 200" нужен нам везде, а вот сообщение формы - только в сообщении формы. Да и писать удобнее: LoginForm.ERR_MSG <- он будет тебе подсказывать, какие атрибуты есть в классе.

Оставляй, как хочешь.

2017-09-25 08:27 UTC, akenoq commented on webpack.config.js
> +		filename: "./static/script/app.js"
done

2017-09-25 08:29 UTC, akenoq commented on static/script/messages.js
> +const messagesLoginForm = {
Ok, поняла

2017-09-25 22:10 UTC, akenoq commented on static/script/CorrectLoginPassword.js
> +        for (let i = 0; i < password.length; i++) {
исправлено

2017-09-25 22:10 UTC, akenoq commented on static/script/RegisterForm.js
>              alert("Вы успешно зарегистрировались!");
теперь в static

2017-09-25 22:11 UTC, akenoq commented on static/script/LoginForm.js
>              alert("Вы вошли на сайт!");
теперь в static

2017-09-25 22:14 UTC, akenoq commented on static/script/LoginForm.js
> +        const t = this;
переделала

2017-09-25 22:15 UTC, akenoq commented on static/script/messages.js
> +const messagesLoginForm = {
done, все сообщения в static классов

2017-09-25 22:21 UTC, akenoq commented on static/script/whoamiMixin.js
> +            const logBox = t.getElementByClass("main-page__user");
ок, изменено

2017-09-25 22:28 UTC, akenoq commented on static/script/Validator.js
> +        if (login==="") {
изменено

2017-09-25 22:40 UTC, akenoq commented on static/script/fieldsCleaner.js
> +            if (elem.nodeName === "INPUT") {
сделала миксин для универсальности

2017-09-25 22:41 UTC, akenoq commented on static/script/Validator.js
> +export default class CorrectLoginPassword {
done

2017-09-26 18:12 UTC, akenoq commented on static/script/RequestToHost.js
> +            const response = JSON.parse(xhr.responseText);
сделаны методы под разные типы запрсов

2017-09-26 21:15 UTC, akenoq commented on Procfile
> +web: node index.js
больше нет

2017-09-26 21:16 UTC, akenoq commented on package.json
> +    "webpack": "^3.5.6"
переместила в devDependencies

2017-09-26 21:16 UTC, akenoq commented on static/.idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
загитигнорила

2017-09-26 21:17 UTC, akenoq commented on static/index.html
> +</html>
ок

2017-09-26 21:17 UTC, akenoq commented on webpack.config.js
> +module.exports = {
убран из зависимостей

2017-09-26 21:19 UTC, akenoq commented on static/script/AddEvent.js
> +export default class AddEvent {
у меня в каждом файлике по одному экспорту но если их много - согласна

2017-09-26 21:19 UTC, akenoq commented on static/script/AddEvent.js
> +        const t = this;
done

2017-09-26 21:19 UTC, akenoq commented on static/script/AddEvent.js
> +                        return errBox.innerHTML = "Некорректный ввод или логин уже существует";
done

2017-09-26 21:21 UTC, akenoq commented on .travis.yml
> +- echo "Hello World!"
пока без тестов ._.

2017-09-26 21:22 UTC, akenoq commented on static/script/Validator.js
> +        this.OK = "ok";
done

2017-09-26 21:23 UTC, akenoq commented on static/script/RequestToHost.js
> +                return callback(xhr, null);
done

2017-09-26 21:24 UTC, akenoq commented on static/script/RegisterForm.js
> +            errorBox.innerHTML = messagesRegisterForm.EMPTY_MESSAGE;
да, я так и думала сделать
позже дизайн еще поменяю чутка

2017-09-26 21:25 UTC, akenoq commented on static/script/PagePresenter.js
> +            {button: "records-page__button-back", nextPage: "main-page"}
done
у каждой страницы свой класс

2017-09-27 07:17 UTC, Antonboom requested changes
Попытаемся выделить основные сущности, которые можно преобразовать в классы, если уж есть попытки в ООП. Быть может, ты найдешь что-нибудь еще, или что-то посчитаешь лишним?

```
Роутер
    |__ Страница
    |       |__ Форма
    |             |__ Поле 
    |             |__ Поле 
    |             |__ Кнопка
    |__ Страница
```

Довольно простая иерархия.
Каждый узел может взаимодействовать с дочерними узлами, например, валидация формы вызывает валидацию всех ее полей и пр.

2017-09-27 07:17 UTC, Antonboom commented on .travis.yml
> +- echo "Hello World!"
Значит здесь сделай test
А в package.json на test пусть будет это echo

2017-09-27 07:17 UTC, Antonboom commented on index.js
> +let port = process.env.PORT || APPLICATION_PORT;
мб const?

2017-09-27 07:17 UTC, Antonboom commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Вот, убери отсюда && exit 1
А в трависе оставь test

2017-09-27 07:17 UTC, Antonboom commented on package.json
> +    "morgan": "^1.8.2",
morgan где-то исползуется?

2017-09-27 07:17 UTC, Antonboom commented on static/script/Debugger.js
> +export default class Debugger {
Не вижу, как ты это используешь((
Ни print(), ни  debugMode

2017-09-27 07:17 UTC, Antonboom commented on static/script/FormValidator.js
> +    static responseOk() {
Лишнее?

2017-09-27 07:17 UTC, Antonboom commented on static/script/FormValidator.js
> +
Где-то у тебя есть пустая строка между определением класса и первым его методом, где-то нет :C

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginForm.js
> +        return "Заполнены не все поля";
Все сообщения в константы
Например, INCORRECT_SYMBOLS_ERR/MSG

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginForm.js
> +    validate(logValue, pasValue, errorBox)
loginValue!
а то путается с логами

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginForm.js
> +        this.logValue = "";
loginValue, passwordValue
loginVal, passwordVal

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginForm.js
> +            alert("Вы вошли на сайт!");
Все сообщения в константы

2017-09-27 07:17 UTC, Antonboom commented on static/script/RegisterPage.js
> +        RegisterPage.workWithRegisterForm();
Правильнее сделать this.form = RegisterForm();
[Даешь композицию!](https://ru.wikipedia.org/wiki/%D0%90%D0%B3%D1%80%D0%B5%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginForm.js
> +            errorBox.innerHTML = this.constructor.msgIncorrectInput();
Обращайся по имени класса.
Или не делай их статичными и используй this - чего мучиться!

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginForm.js
> +        this.getElementByClass("login-form__button").addEventListener("click", () => {
Лучше бы, конечно, иметь класс формы, который валидирует свои поля и сам себя сабмитит, куда нужно. Но ладно

2017-09-27 07:17 UTC, Antonboom commented on static/script/LoginPage.js
> +        LoginPage.workWithLoginForm();
Тут то же самое, что и со страницей регистрации.
У тебя плохое понимание ООП - где-то грустит одна Иванова.

2017-09-27 07:17 UTC, Antonboom commented on static/script/MainClass.js
> +class MainClass {
Очень классное название! (нет)
Application
App
MainApp
Что-нибудь, что даст понять извне, за что этот класс отвечает.
И не нужно использовать имя типа в имени: class - Main**Class**.
😠

2017-09-27 07:17 UTC, Antonboom commented on static/script/MainClass.js
> +        Object.assign(PagePresenter.prototype, elementPresenter);
Почему бы просто не унаследовать PagePresenter от elementPresenter?
К слову, второе - снова очень неподходящее название.
У тебя внутри нет ничего, что показывает элемент. 
Этот класс:
1) Вспомогательный
2) Содержит функции, помогающие обратиться к элементу
Почему presenter????
И вообще класс из одной функции? Может просто вынести ее в utils.js и импортировать где нужно?

2017-09-27 18:19 UTC, akenoq commented on static/script/MainClass.js
> +class MainClass {
ok

2017-09-27 18:29 UTC, akenoq commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
ok

2017-09-27 18:33 UTC, akenoq commented on index.js
> +let port = process.env.PORT || APPLICATION_PORT;
да

2017-09-27 21:12 UTC, akenoq commented on package.json
> +    "morgan": "^1.8.2",
уже нет

2017-09-27 21:19 UTC, akenoq commented on static/script/FormValidator.js
> +
ок, поправила

2017-09-27 21:50 UTC, akenoq commented on static/script/FormValidator.js
> +    static responseOk() {
да. перенесла в статик, как и везде

2017-09-27 22:47 UTC, akenoq commented on static/script/LoginForm.js
> +        return "Заполнены не все поля";
сейчас сообщения везде в static, в прошлых комментах, вроде, на этом остановились Оо

2017-09-27 23:04 UTC, akenoq commented on static/script/LoginForm.js
> +            errorBox.innerHTML = this.constructor.msgIncorrectInput();
ок, по имени класса. оставлю статичными, так вернее

2017-09-27 23:04 UTC, akenoq commented on static/script/LoginForm.js
> +            alert("Вы вошли на сайт!");
ок

2017-09-28 10:21 UTC, akenoq commented on static/script/LoginForm.js
> +        this.logValue = "";
ok

2017-09-28 10:25 UTC, akenoq commented on static/script/RegisterPage.js
> +        RegisterPage.workWithRegisterForm();
согласна, забыла изменить

2017-09-28 10:43 UTC, akenoq commented on static/script/LoginForm.js
> +    validate(logValue, pasValue, errorBox)
fixed

2017-09-28 14:35 UTC, akenoq commented on static/script/MainClass.js
> +        Object.assign(PagePresenter.prototype, elementPresenter);
У меня миксин, т.к. у меня метод getElementByClass() помимо страниц используется еще и в формах, а они не наследуются от Page
Название заменила и еще тут поправила, PagePresenter не нужен этот метод

2017-09-28 14:59 UTC, akenoq commented on static/script/Debugger.js
> +export default class Debugger {
выпиливала прост
сейчас, например, при старте приложения печатает в консоль, если DEBUG_MODE = true

2017-09-28 17:54 UTC, Antonboom requested changes
Ты молодец!
Финальный рывок?

2017-09-28 17:54 UTC, Antonboom commented on static/script/Page.js
> +        let t = this;
Стрелочные функции?

2017-09-28 17:54 UTC, Antonboom commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
forEach(()=>{})?

2017-09-28 17:54 UTC, Antonboom commented on static/script/Page.js
> +        buttons.forEach(function (button, i, buttons) {
Стрелочные функции?

2017-09-28 17:54 UTC, Antonboom commented on static/script/Page.js
> +            t.getElementByClass(button.button).addEventListener("click", function () {
Стрелочные функции?

2017-09-28 17:54 UTC, Antonboom commented on static/script/RequestToHost.js
> +        const xhr = new XMLHttpRequest();
Слабо заменить на fetch()?
https://learn.javascript.ru/fetch

2017-09-28 17:54 UTC, Antonboom commented on static/script/fieldsCleaner.js
> +        for (let i = 0; i < fields.length; i++) {
forEach?

2017-09-28 17:54 UTC, Antonboom commented on static/script/whoamiMixin.js
> +                return loginBox.innerHTML = "Привет, Гость!";
сообещние -> константа

2017-09-29 12:48 UTC, akenoq commented on static/script/whoamiMixin.js
> +                return loginBox.innerHTML = "Привет, Гость!";
done

2017-09-29 12:48 UTC, akenoq commented on static/script/fieldsCleaner.js
> +        for (let i = 0; i < fields.length; i++) {
done

2017-09-29 12:48 UTC, akenoq commented on static/script/RequestToHost.js
> +        const xhr = new XMLHttpRequest();
пока xhr

2017-09-29 12:49 UTC, akenoq commented on static/script/Page.js
> +            t.getElementByClass(button.button).addEventListener("click", function () {
done

2017-09-29 12:49 UTC, akenoq commented on static/script/Page.js
> +        buttons.forEach(function (button, i, buttons) {
ок

2017-09-29 12:49 UTC, akenoq commented on static/script/Page.js
> +        let t = this;
ок

2017-09-29 12:50 UTC, akenoq commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
Сделала так, т.к. pages - это htmlcollection и forEach нет
Пока так, потом можно прикрутить к прототипу щкУфср

2017-09-29 13:05 UTC, Antonboom approved these changes

2017-09-29 13:05 UTC, merged