Add records table + pug + fixed styles + linter
frontend-park-mail-ru/2017_2_brainstorm pull request #8
Opened 2017-10-07 10:46 UTC by akenoq

2017-10-07 19:50 UTC, Antonboom requested changes
Будет считать, что поверил.
Незначительные правочки

2017-10-07 19:50 UTC, Antonboom commented on .eslintrc.json
> +{
Что-то маловато правил.
Может, украдем у какой-нибудь крутой компании пример этого файла?)

2017-10-07 19:50 UTC, Antonboom commented on changelog.txt
> -1.0.2
 Зачем ты удалила старое?)))

changelog и нужен для того, чтобы видеть историю изменений.
Просто выше пиши новые

2017-10-07 19:50 UTC, Antonboom commented on package.json
> +    "eslint": "./node_modules/.bin/eslint ./static/script"
Хочу, чтобы травис знал об этом скрипте.

2017-10-07 19:50 UTC, Antonboom commented on static/script/LoginForm.js
> +        this.getElementByClass("login-page__button-back").addEventListener("click", () => {this.clearForm();});
Надо найти правило, которое хочет пробелы.
Здесь обычно пишут так:
```
() => { this.cleanForm(); };
```
А так, как хочешь

2017-10-07 19:50 UTC, Antonboom commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
forEach()?

2017-10-07 19:50 UTC, Antonboom commented on static/script/RecordsPage.js
> +        let template = require("./../views/records-page.pug");
Можно в Page вынести templatePath для страницы

2017-10-07 19:50 UTC, Antonboom commented on static/script/RecordsPage.js
> +                return alert("Empty TOP");
Ты серьезно пользователю алерт покажешь?

2017-10-07 19:51 UTC, akenoq commented on changelog.txt
> -1.0.2
ок =)

2017-10-07 19:52 UTC, akenoq commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
живая коллекция, по ней forEach не пройтись

2017-10-07 19:53 UTC, akenoq commented on static/script/RecordsPage.js
> +                return alert("Empty TOP");
уберу вообще или в бокс с ошибкой дуду писать

2017-10-07 19:58 UTC, Antonboom commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
РК не проходят даром?)
А как сделать так, чтобы можно было, интересно же?

2017-10-07 20:38 UTC, akenoq commented on package.json
> +    "eslint": "./node_modules/.bin/eslint ./static/script"
теперь знает

2017-10-07 20:38 UTC, akenoq commented on static/script/LoginForm.js
> +        this.getElementByClass("login-page__button-back").addEventListener("click", () => {this.clearForm();});
оставлю так - привычнее

2017-10-07 20:47 UTC, akenoq commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
Я знала это на рк :(
И даже тебе здесь это писала в прошлом пуллреквесте под эти же комментом)
Для его использования надо прикрутить forEach в прототип htmlcollection

2017-10-07 22:27 UTC, Antonboom commented on static/script/Page.js
> +        for (let i = 0; i < pages.length; i++) {
Или просто использовать call
https://learn.javascript.ru/call-apply

2017-10-10 20:47 UTC, Antonboom approved these changes
С пивом потянет

2017-10-10 20:47 UTC, merged