Routing
frontend-park-mail-ru/2017_2_brainstorm pull request #9
Opened 2017-10-12 11:34 UTC by akenoq

2017-10-12 16:50 UTC, Antonboom commented on changelog.txt
> +Роутинг
В самом верху файла - самые последние изменения.
Не наоборот))

2017-10-12 16:50 UTC, Antonboom commented on package.json
> +    "css-loader": "^0.28.7",
Здесь точно нет лишних (dev) зависимостей?

2017-10-12 16:51 UTC, Antonboom commented on static/index.html
> +    <!--<link rel = "stylesheet" type = "text/css" href = "./styles/bundle.css"/>-->
???
Где TODO, FIXME или что-нибудь, что заставит меня не выпилить этот комментарий

2017-10-12 16:51 UTC, Antonboom commented on static/script/InfoPage.js
> +    static pagePath() {
static path = "/info";

не короче?))
но как хочешь

2017-10-12 16:52 UTC, Antonboom commented on static/script/LoginForm.js
> +        Object.assign(LoginForm.prototype, whoamiMixin,fieldsCleaner);
Почему линтер разрешил тебе не поставить пробел после запятой?

2017-10-12 16:52 UTC, Antonboom commented on static/script/Page.js
> +            document.querySelector("."+button.button).addEventListener("click", () => {
 Здесь снова линтер спит по пробелам

2017-10-12 16:54 UTC, Antonboom commented on static/script/PagePresenter.js
> +            Page.showOnlyOnePage("main-page");
Почему ты не можешь назвать его роутер?)
Или что это вообще такое?
Я не понимаю, что значит "Страница.ПокажиТолькоОднуСтраницу"

2017-10-12 16:54 UTC, Antonboom requested changes
Вроде норм.
Молодечик

2017-10-12 16:56 UTC, akenoq commented on changelog.txt
> +Роутинг
ок =)

2017-10-12 16:57 UTC, akenoq commented on package.json
> +    "css-loader": "^0.28.7",
есть это осталось от попыток собрать css в пак

2017-10-12 16:57 UTC, akenoq commented on static/script/InfoPage.js
> +    static pagePath() {
согласна, поправлю

2017-10-12 17:56 UTC, akenoq commented on static/index.html
> +    <!--<link rel = "stylesheet" type = "text/css" href = "./styles/bundle.css"/>-->
ok, добавлю коммент, если не выпилю

2017-10-12 18:03 UTC, akenoq commented on static/script/PagePresenter.js
> +            Page.showOnlyOnePage("main-page");
Переименую :Р
Метод отображает нужную страницу, можно перенести в Роутер

2017-10-12 18:04 UTC, akenoq commented on static/script/LoginForm.js
> +        Object.assign(LoginForm.prototype, whoamiMixin,fieldsCleaner);
надо правило добавить

2017-10-12 21:48 UTC, akenoq commented on static/script/Page.js
> +            document.querySelector("."+button.button).addEventListener("click", () => {
добавила правила

2017-10-12 22:35 UTC, akenoq commented on package.json
> +    "css-loader": "^0.28.7",
пока убрала

2017-10-13 08:32 UTC, Antonboom approved these changes
🔥

2017-10-13 08:32 UTC, merged